### ISSUE TITLE
move to next track when playing an album track

### ISSUE THREAD

**Issue by foss-** [prayag17/Blink#182]
**Is your feature request related to a problem? Please describe.**
Currently when playing a track from an album playback stops once the track has been played.

**Describe the solution you'd like**
It would be great if JellyPlayer moved to the next track of the album and continued playing that until all remaining album tracks have been played.

JellyPlayer Alpha 2
macOS 13.6

**Comment by prayag17** [comment]
Yeah, continuous playback has yet to be implemented.

**Comment by prayag17** [comment]
Continuous playback for audio should work in latest commit

**Comment by foss-** [comment]
Should this be working in https://github.com/prayag17/JellyPlayer/releases/tag/v1.0.0-test02 already or is that limited to the changes for #119?

**Comment by prayag17** [comment]
It was already working

**Comment by foss-** [comment]
Not sure I understand. It is not working here on macOS 13.6 and the just released test-build. Test build plays a single track of an album and does not play the next song. It also doesn't play another song when manually selecting any other track.

**Comment by prayag17** [comment]
Wdym manually selecting track?

**Comment by foss-** [comment]
Clicking a track to start playing. It won't play after one track has played. There is the circular animation around the play button, but no audio will start playing.

Just discovered this does not apply to all albums and now wondering what differentiates the problematic albums I see this issue with from those where manually selecting a track works. However even for the albums where manual selecting and playing a track works, but playing a track from an album still won't automatically move to the next track.

**Comment by prayag17** [comment]
Check if your album has track numbers

**Comment by foss-** [comment]
It does:

<img src="[IMAGE_URL](https://github.com/prayag17/JellyPlayer/assets/5708172/9e9fecac-afd0-44d4-90c1-cc37d0fec073)" width="450">

**Comment by prayag17** [comment]
Can you try changing the server to `https://demo.jellyfin.org/stable`, and check if the album tracks there play in a series?

**Comment by foss-** [comment]
`Change server` took me to a blank view with no fields to enter a server.

<img src="https://github.com/prayag17/JellyPlayer/assets/5708172/97e22132-2cf8-45c1-83c3-430cb021920b" width="450">

**Comment by prayag17** [comment]
Don't use the change server instead remove the server by clicking on the user profile image in the header. Change server is yet to be implemented

**Comment by foss-** [comment]
Played the binaerpilot promo album and indeed it continued playing track number 4 after track number 1. So something is wrong with my server setup? It is Jellyfin 10.8.11.

<img src="https://github.com/prayag17/JellyPlayer/assets/5708172/c54775cf-658e-4d39-a365-91068486fcca" width="450">

**Comment by prayag17** [comment]
Well it is your server that's causing this issue, but idk what issue client has with your server

**Comment by prayag17** [comment]
Can you send me a screenshot of the console(left click and inspect) when the music ends

**Comment by foss-** [comment]
Sidenote: Playing tracks of an album works as expected in Jellyfin Media Player.

Here is the requested screenshot. Note: the initial 7 errors `Failed to load resource` showing initially. Checked the URLs and that is a few videos lacking a primary image, so seems unrelated.

Once the first track comes to the end, the following error shows:
```
[Error] Unhandled Promise Rejection: EncodingError: Decoding failed
	l (index-0a18ac56.js:422:6016)
```

<img src="https://github.com/prayag17/JellyPlayer/assets/5708172/f197fb14-6c25-4d40-be84-08eee865dc3e" width="450">

**Comment by prayag17** [comment]
Can you run the app as mentioned in Readme?

**Comment by foss-** [comment]
Mentioned where? Can you elaborate how to do that?

**Comment by prayag17** [comment]
https://github.com/prayag17/JellyPlayer?tab=readme-ov-file#-prerequisites

Start from here

**Comment by foss-** [comment]
Oh that is maybe out of scope for me or will have to be postponed until the needed time is available as sadly I am not familiar with those mechanisms.

**Comment by prayag17** [comment]
Ok

**Comment by foss-** [comment]
Thanks for digging into this. How does Jellyfin WebUI resolve this or are they not using the web audio api?

**Comment by prayag17** [comment]
Maybe they don't use MP3, I am not really sure

**Comment by foss-** [comment]
Feishin just released 0.4.1 and they seem to have fixed identical issue as per the release notes:
`Fixed playback not automatically continuing to the second song in the queue when starting playback from a fresh restart`
https://github.com/jeffvli/feishin/releases/tag/v0.4.1

**Comment by prayag17** [comment]
They seem to be using Electron which uses chromium which does not have this issue, the same reason why windows doesn't have this issue

**Comment by foss-** [comment]
Do you know if an open issue for the web audio API problem exists already and if yes, could you share the link?

**Comment by prayag17** [comment]
I have switched from WebAudio Api to HtmlMedia element for audio playback which might fix this issue.

**Comment by foss-** [comment]
Is the latest build https://github.com/prayag17/JellyPlayer/releases/tag/v1.0.0-dev%40abca227 ?
That shows as Version 1.0.0 (20231208.093929) which is the version I reported the current behavior for yesterday. Can you point me to the newer build please.

**Comment by prayag17** [comment]
https://github.com/prayag17/JellyPlayer/releases/tag/v0.0.1-dev%40874646a

this is the latest build.

**Comment by foss-** [comment]
Same - while the second track does play (improvement over previous situation) the waveform indicator is not moving when the second track is playing.

**Comment by prayag17** [comment]
Hey @foss- , can you try the latest nightly build aand check if the issue still persists

**Comment by foss-** [comment]
0.0.7-dev (20241123.160825) verified that this now moves to the next track of an album 🙌 🚀

**Comment by prayag17** [comment]
I will keep this issue open for now

**Comment by prayag17** [comment]
Hey @foss-, I just pushed a commit to fix, you can try the latest nightly build to verfiy if it works now

**Comment by foss-** [comment]
Sure, can you hint me at the build to test. I Was looking at https://github.com/prayag17/Blink/actions/runs/11989753138 and could not find a build but I may be looking at the wrong place.

**Comment by prayag17** [comment]
https://github.com/prayag17/Blink/actions/runs/11989217200

**Comment by foss-** [comment]
0.0.7-dev (20241123.175537) works fine. Tracks skip to next skip no matter how often a track is interacted with.

So happy to call this fixed. Thanks for your work 🙌  🚀
