### ISSUE TITLE
Unable to install .deb on ubuntu 24.04

### ISSUE THREAD

**Issue by accforgithubtest** [prayag17/Blink#327]
**Describe the bug**
Unable to install the latest deb package on Ubuntu 24.04 LTS system.
Issue seems to be that JellyPlayer is looking for older version libwebkit2gtk-4.0-37, while the latest Ubuntu 24.04 LTS has the newer version libwebkit2gtk-4.1-0.

**To Reproduce**
1. Download the latest .deb file from github releases.
2. Try to install using apt and see Below error ehile trying to install
```sh
$ sudo apt install ./jelly-player_0.0.5-dev_amd64.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'jelly-player' instead of './jelly-player_0.0.5-dev_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 jelly-player : Depends: libwebkit2gtk-4.0-37 but it is not installable
E: Unable to correct problems, you have held broken packages.

```

3. Checking for available versions of  libwebkit2gtk
```sh
$ sudo apt install libwebkit2gtk-4.
libwebkit2gtk-4.0-doc  libwebkit2gtk-4.1-0    libwebkit2gtk-4.1-dev
```

4. Newer version of libwebkit2gtk-4.1-0 is already installed on the Ubuntu 24.04 LTS system
```sh
$ sudo apt install libwebkit2gtk-4.1-0
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libwebkit2gtk-4.1-0 is already the newest version (2.44.0-2).
libwebkit2gtk-4.1-0 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

**Expected behavior**
Use the already available libwebkit2gtk-4.1-0.

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04 LTS
 - Browser N/A
 - Version jelly-player_0.0.5-dev_amd64.deb

**Comment by prayag17** [comment]
You can try building JellyPlayer on your machine for the time being... I will look into this

**Comment by accforgithubtest** [comment]
thank you @pypp  and @prayag17  ! I have since downgraded to 22.04 because of audio issues in 24.04.

I have severe slowness when I start the application. For example, I have a 4k monitor, and initially the application opens in a tiny window. Maximizing it just hangs the application. Can you pls let me know if there are any logs I can share ?

**Comment by pypp** [comment]
unfortunately I doin't think I can help you with that.

**Comment by prayag17** [comment]
Linux has weird performance issues that don't seem to show up in windows or mac, this issue is already reported here and I am working on performance improvement
