### ISSUE TITLE
[Feat] Jellyfin 10.9 Support

### ISSUE THREAD

**Issue by prayag17** [prayag17/Blink#337]
Blink "works" with Jellyfin 10.9 and no API changes needed to be implemented but with Jellyfin 10.9 new features like **TrickPlay** and **Lyrics** have been added. I have created this issue to track the implementation of these features directly into Blink (formerly JellyPlayer)

- [x] Trickplay support with chapter marks in player
- [x] Lyrics display while playing music

**Comment by xAphex** [comment]
any updates with 10.9 support?

thanks

**Comment by prayag17** [comment]
Jellyfin 10.9 already works with Blink, this issue just tracks the new features that have been implemented in Jellyfin 10.9

**Comment by xAphex** [comment]
> Jellyfin 10.9 already works with Blink, this issue just tracks the new features that have been implemented in Jellyfin 10.9

when can we expect a new update?
last one was in February.

**Comment by prayag17** [comment]
Next dev builds will be released with Jellyfin 10.9 specific features and as for Alpha release you can track #338
