### ISSUE TITLE
[Feat] Show hour and minutes when hovering on progress bar

### ISSUE THREAD

**Issue by exnihilo-creatio** [prayag17/Blink#339]
**Is your feature request related to a problem? Please describe.**
Show a `hh:mm:ss`  when hovering on the progress bar for videos.

**Describe the solution you'd like**
A tooltip that shows the current progress or the timestamp when hovering on the progress bar for videos.

**Comment by prayag17** [comment]
The player already shows progress slider value where the current time is rendered but only while scrubbing

**Comment by exnihilo-creatio** [comment]
Ok, then ideally it also shows when it is not scrubbing when it is needed to jump to a specific time without scrubbing.

**Comment by prayag17** [comment]
Oh ok got it

**Comment by prayag17** [comment]
I have added this feature, you can try it out in the latest nightly build
