### ISSUE TITLE
Unable to display Chinese subtitles properly

### ISSUE THREAD

**Issue by Steven-Zhl** [prayag17/Blink#340]
**Describe the bug**

* When I use JellyPlayer to play a video, the external subtitles corresponding to the video are not displayed normally, but some boxes are displayed. However, Chinese characters in video information can be displayed normally, such as episode titles.
* My subtitles are in Chinese and the encoding is UTF-8.

**To Reproduce**

1. Play any video using external subtitles (such as .ass or .srt files) and the language is Chinese.

**Expected behavior**

1. Chinese subtitles that can be displayed normally.

**Screenshots**

![image](https://github.com/prayag17/JellyPlayer/assets/80385790/e4a8598a-745f-4524-86ec-cbea0ab48954)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Version: 
   - Jellyfin 10.9.2
   - JellyPlayer 0.0.5-dev

**Additional context**

A similar problem has occurred in Jellyfin before. The reason is that the default font does not contain characters such as Chinese. I hope JellyPlayer can use a more compatible font (such as Noto Sans) or allow users to use their own fonts.

**Comment by prayag17** [comment]
I might have forgotten to bundle Chinese fonts in Blink(previously known as jellyplayer)... I will add it in the next release

**Comment by Steven-Zhl** [comment]
Thank you so much!

**Comment by OnismIS** [comment]
> I might have forgotten to bundle Chinese fonts in Blink(previously known as jellyplayer)... I will add it in the next release我可能忘记在 Blink（以前称为 jellyplayer）中打包中文字体了……我将在下一个版本中添加

It seems that this problem still exists in the latest nightly version.

![Image](https://github.com/user-attachments/assets/2a6d7c28-2c28-4270-853f-6b5ace789270)
