### ISSUE TITLE
[Feat] Show Currently Playing Show/Movie Title in the Window Title

### ISSUE THREAD

**Issue by exnihilo-creatio** [prayag17/Blink#348]
**Is your feature request related to a problem? Please describe.**
When playing a series on a different screen than the main one it is not possible to glance and see which movie or series and episode number is playing. 

**Describe the solution you'd like**
Show the movie title in the Window Title and in the case of a show the Series Title - Episode Number and Episode name if available, i.e. 'Star Trek: Discovery | S5:E1 Red Directive'.

Context is when the window in full size mode, but not fullscreen.

**Comment by prayag17** [comment]
Tauri does not allow changing window title in runtime (yet) so there is no way to implement this feat atleast for now
