### ISSUE TITLE
[Bug] Movie and Album Covers are all displayed in different sized regardless of resolution

### ISSUE THREAD

**Issue by NicolasKemp** [prayag17/Blink#380]
**Describe the bug**
Images appear all in different sizes in movies, music, shows, etc menus. 

I do not know the reason of this, my first theory was because of image resolution, but it doesnt seem to be the case as you'll seem by the next resolutions and looking at the screenshots below.
Coraline: 1600x2400
Deadpool: 2000x3000
Dungeons and Dragons: 2000x3000

**To Reproduce**
1. Go to the Movies section of the app
2. look?

**Expected behavior**
Every movie and album cover should be displayed the same size.

**Screenshots**
![image](https://github.com/user-attachments/assets/0b558646-03a5-4c5e-a29e-ce88efe1ec0e)
![image](https://github.com/user-attachments/assets/27ef9012-d716-42c0-9519-f642f18a9495)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Blink software(?
 - Version Dev 0.0.5

**Additional context**
I tried uninstalling and deleting all data and installing again.

**Comment by prayag17** [comment]
Hey @NicolasKemp, can check if this is still an issue in v0.0.6-dev?

**Comment by NicolasKemp** [comment]
> Hey @NicolasKemp, can check if this is still an issue in v0.0.6-dev?

Yes, it is still an issue
![image](https://github.com/user-attachments/assets/2b79a0f6-0e47-4253-8383-558e53bfd0a3)

**Comment by Magusbear** [comment]
Same problem happening to me.

Client version: 0.0.6-dev
Jellyfin Version: 10.9.11
OS: Windows 11

![image](https://github.com/user-attachments/assets/2f6af425-5084-441f-873d-d84bbce082fa)

**Comment by coriscm14** [comment]
+1 still happening
OS: Windows 11 Pro
Version: 0.0.7-dev
Jellyfin Version: 10.10.3
Screen Resolution: 2560x1440
![Screenshot 2024-11-25 051552](https://github.com/user-attachments/assets/7106d7af-0639-48aa-8ac5-9215457453a6)

**Comment by prayag17** [comment]
should be fixed in the latest nightly
