### ISSUE TITLE
[Bug]:Cant launch Blink on Windows 10

### ISSUE THREAD

**Issue by xAphex** [prayag17/Blink#382]
**Describe the bug**
Every time i open Blink 0.0.6-dev it launches and closes immediately, but the program appears open in task manager.

**To Reproduce**
1. Launch Blink 0.0.6-dev.

**Expected behavior**
Program should start normally and show UI.

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2 19045.4894

**Comment by kloon15** [comment]
Works fine for me on 19045.4894

**Comment by Uncle-Tio** [comment]
Same behavior on W11 (24H2 - 26100.2033)

**Comment by prayag17** [comment]
Can You try the latest night build?
You can find that [here](https://github.com/prayag17/Blink/actions/runs/11859032859)

**Comment by xAphex** [comment]
> Can You try the latest night build? You can find that [here](https://github.com/prayag17/Blink/actions/runs/11859032859)

nothing changed, same issue.

**Comment by xAphex** [comment]
i just tested version 0.0.7 and the issue persists.

**Comment by prayag17** [comment]
Can you run the app through command line and share the output here?

**Comment by xAphex** [comment]
> Can you run the app through command line and share the output here?

![image](https://github.com/user-attachments/assets/2d84870e-c6c1-4a87-8f56-c3844ac060e2)

**Comment by prayag17** [comment]
just do `./blink.exe` maybe that might spit out some error message

**Comment by Uncle-Tio** [comment]
Latest update (Blink_0.0.7-dev) now works for me.

A little extra information (if you aren't already aware), videos in HEVC-10bit don't seem to work, AVC-8bit and AV1-10bit seem ok. If you want some kind of log you can ask me (Jellyfin 10.9.11)

**Comment by prayag17** [comment]
HEVC-10bit might not be supported by windows's MediaFoundation codec on your system

**Comment by xAphex** [comment]
> just do `./blink.exe` maybe that might spit out some error message

![image](https://github.com/user-attachments/assets/e45666c5-5434-46f9-84e3-8ecf2dd4fb53)

**Comment by prayag17** [comment]
This is very weird, I can't seem to recreate this issue and I don't see any errors like this mentioned anywhere in Tauri's issues page.

**Comment by xAphex** [comment]
> This is very weird, I can't seem to recreate this issue and I don't see any errors like this mentioned anywhere in Tauri's issues page.

is there a program/debuger i can use to look more into this issue?

**Comment by xAphex** [comment]
@prayag17 https://stackoverflow.com/questions/76230179/tauri-app-installs-successfully-but-doesnt-run

`But for you there could be some other error that causing the same issue, so i recommend before creating the release build, create a debug build using the command "cargo tauri build --debug", this will create a debug folder in your target folder. If you install the app from there and run it, it will launch a tarminal with the app that will show all the error (As long as the error is after the app builder runs, if the error is happing before the builder runs then thats the reason your app is not even starting)`

**Comment by prayag17** [comment]
you can try the debug build from here :
https://github.com/prayag17/Blink/actions/runs/12010190732

**Comment by xAphex** [comment]
> you can try the debug build from here : https://github.com/prayag17/Blink/actions/runs/12010190732

`Warning: No files were found with the provided path: src-tauri/target/release/bundle/*. No artifacts will be uploaded.`

**Comment by xAphex** [comment]
> I'm sorry, I forgot to update the upload target in CI. You can get the new debug nightly builds from now on.
> 
> https://github.com/prayag17/Blink/actions/runs/12013243845

![image](https://github.com/user-attachments/assets/4a0f213a-1e41-4aea-a6ed-dd9e819d167d)

**Comment by xAphex** [comment]
https://stackoverflow.com/questions/76230179/tauri-app-installs-successfully-but-doesnt-run

`And for the error why opening the .exe file does nothing, that's because your app is running into an error even before the tauri::Builder was called in your main.rs file and causing it to crash before opening the app.`

**Comment by xAphex** [comment]
> There is really no way for me to debug an error if I can't even recreate it. My best guess is that tauri-plugin-store is not properly working with your system and I have not seen this issue reported by anyone else.
> 
> You can try completely deleting Blink from your system.(Delete all folders with com.prayag17 at AppData/Roaming and AppData/Local and AppData/LocalLow AFTER UNINSTALLING THE APP)

uninstalled the program using `HiBit Uninstaller` (which removed left over files/registry), also used `Everything` program to search for anything left of `prayag17` and removed it, program still doesnt launch.

https://github.com/tauri-apps/tauri/issues/11674

Do you thing the problem could because of this? Do you have any Dark Mode code in Blink?

**Comment by xAphex** [comment]
https://stackoverflow.com/questions/76044638/built-tauri-app-closes-unexpectedly-with-no-errors-reading-json-file

Could it be this? Dude forgot to add the Paths to his json file in his tauri.conf.json file.

**Comment by prayag17** [comment]
> https://github.com/tauri-apps/tauri/issues/11674
  Do you thing the problem could because of this? Do you have any Dark Mode code in Blink?

I don't think this is related to your issue, and no, there is no dark mode like stated in the linked issue.

> https://stackoverflow.com/questions/76044638/built-tauri-app-closes-unexpectedly-with-no-errors-reading-json-file
  Could it be this? Dude forgot to add the Paths to his json file in his tauri.conf.json file.

This can't be the issue here since it works fine everywhere else. If there were some configuraation errors in tauri.conf.json or vite.config.js the app would not even compile let alone run on other systems. 

I still doubt this issue is caused by something I did but I am still going to keep this issue open (for now...)

**Comment by xAphex** [comment]
I think i figured out the problem. i have microsoft edge uninstalled from my machine, so i dont have webview2, which is something Blink requires.

Was looking at problems from other people with their tauri programs crashing and many mentioned webview2 and then it clicked in my head that i have it uninstalled.

**Comment by prayag17** [comment]
Oh that makes a ton of sense. 

Btw you can install WebView2 without installing edge, just get the WebView2 Runtime from their website and you should be good to go

**Comment by xAphex** [comment]
> Oh that makes a ton of sense.
> 
> Btw you can install WebView2 without installing edge, just get the WebView2 Runtime from their website and you should be good to go

yup, i was correct, installed webview2 runtime, and it now launches.

also, can you fix this problem:
![image](https://github.com/user-attachments/assets/3d99d097-d7ed-4fec-8b04-b1ef94cec941)
