### ISSUE TITLE
Can't play content `TypeError: undefined is not an object (evaluating 'j[L].Id')`

### ISSUE THREAD

**Issue by foss-** [prayag17/Blink#383]
**Describe the bug**
When trying to play a movie and clicking "Continue Watching", content won't play. Instead error message `TypeError: undefined is not an object (evaluating 'j[L].Id')` is shown. Video is AV1 SDR. Other video files also won't play and music won't play. Not sure if this is a specific issue with a file or rather a broader more general issue after the current changes for 0.0.6.

All tested files do play in Jellyfin Media Player desktop client.

**To Reproduce**
Play video file or music.

**Expected behavior**
Start playback.

**Desktop (please complete the following information):**
 - OS: macOS 14.6.1
 - Version 0.0.6-dev (20240906.203224)
- JF 10.9.10

**Comment by prayag17** [comment]
This issue should be fixed in latest dev builds

**Comment by foss-** [comment]
I don't understand. Issue was filed against [0.0.6](https://github.com/prayag17/Blink/releases/tag/v0.0.6-dev). Is there a newer release I am not aware of to test against?

**Comment by prayag17** [comment]
Sorry @foss- I meant nightly build

**Comment by foss-** [comment]
Can you share a link to a nightly build? If not, I'll wait for the next pre-release.
