### ISSUE TITLE
extreme ui lag making it unusable

### ISSUE THREAD

**Issue by AEnterprise** [prayag17/Blink#385]
**Describe the bug**
Extreme lag trying to use the app, 5+ second delays when just scrolling or hovering over stuff before the ui catches up. even clicking on anything takes multiple seconds for anything to happen

**To Reproduce**
Try to use the app. just scrolling navigating around, hovering. not a single part of the app doesn't lag

**Expected behavior**
The app to be usable and not have 5+ seconds delays when scrolling or clicking anything, hovering, basically anything rendering related

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch linux
 - Browser none? running the exe locally and can't find any instructions on how to even open this in a browser
 - Version: tried the latest appimage for 0.06-dev, tried building the exe locally and tried the latest master. all have this issue
 

**Additional context**

**Comment by prayag17** [comment]
Appimage performance issue is already a known issue, unfortunately tho it seems to be caused by Tauri and not by blink's code.

**Comment by AEnterprise** [comment]
i also tried using the executable directly, that had the same issue

**Comment by davidosdr** [comment]
Same

**Comment by prayag17** [comment]
Arch Linux has performance issues which are related to Tauri and not something I can fix myself, tho I am trying to improve performance of Blink but Arch Linux would still stay laggy until Tauri moved away from webkitgtk2
