### ISSUE TITLE
Cannot play series, error: `TypeError: Cannot read properties of undefined (reading 'Id')`

### ISSUE THREAD

**Issue by vikingnope** [prayag17/Blink#391]
**Describe the bug**
Tried playing an episode from a series particularly Family Guy Season 7 Episode 12, and got the following error: `TypeError: Cannot read properties of undefined (reading 'Id')`

**Expected behavior**
Should just work normally

**Screenshots**
![image](https://github.com/user-attachments/assets/1c106f46-eb74-4a47-bd58-f7d8f600e51b)

![image](https://github.com/user-attachments/assets/05973a1c-27fc-4fca-beb7-3c74ead8d418)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: n/a
 - Version: 0.0.6-dev
 - Jellyfin: 10.9.11

**Comment by prayag17** [comment]
This issue should be fixed in the latest nightly build
