### ISSUE TITLE
No subtitles are displayed

### ISSUE THREAD

**Issue by kloon15** [prayag17/Blink#394]
**Describe the bug**
No subtitles are being displayed, the cogwheel shows the available subtitles but selecting any of them makes no difference.

**To Reproduce**
1. Start playback
2. Select subtitle with the cogwheel on top right
3. Nothing is displayed

**Expected behavior**
Subtitles are being displayed on screen.

**Screenshots**
![image](https://github.com/user-attachments/assets/25d8a7d7-6ea6-474c-b5e4-d2ad5f54bf7e)

**Desktop (please complete the following information):**
 - OS: Win10 19045.4894
 - Version: 0.0.6-dev

**Additional context**
Works fine with official client or Findroid on Android.

**Comment by prayag17** [comment]
DVDSUBS and PUGSSUB formats are not supported by Blink (yet...)

**Comment by kloon15** [comment]
> DVDSUBS and PUGSSUB formats are not supported by Blink (yet...)

Oh it was just an example, not even SRT works.
