### ISSUE TITLE
Android / Google TV app? 

### ISSUE THREAD

**Issue by CyberB1aze** [prayag17/Blink#416]
**Is your feature request related to a problem? Please describe.**
Not sure if this is the right avenue to request something like this, but this application looks amazing and it would be awesome if it was possible to get this as an app for Android phones and google tv. 

**Describe the solution you'd like**

**Describe alternatives you've considered**
This is the best looking jellyfin Client I have come accross and it would be fantiastic if it could run on a tv os. 

**Additional context**

**Comment by prayag17** [comment]
Refer to this:
https://github.com/prayag17/Blink/discussions/386#discussioncomment-11136789
