### ISSUE TITLE
UI doesn't load Windows 11

### ISSUE THREAD

**Issue by OnismIS** [prayag17/Blink#417]
**Describe the bug**
UI cannot load, even after uninstallation and reinstallation. Just like #115.

**Screenshots**
![image](https://github.com/user-attachments/assets/b6074114-edc0-4693-8296-bbcc211ac5bb)
![image](https://github.com/user-attachments/assets/cf756307-82d8-4c90-808e-5fe461ebee14)

**Desktop (please complete the following information):**
 - OS: win11 24h2
 - Version  v0.0.6-dev
 - Jellyfin Version 10.10.0
 
**Additional context**
When I log in to the server and use Quick Connect, an error appears on the page, and restarting the software cannot display UI.

**Comment by OnismIS** [comment]
After testing, CI version #497 is normal, but the updated version has this issue.
I encountered error #391 in the release version, so I tried the latest CI version.

**Comment by prayag17** [comment]
I have found the source of this issue and it has to do with the new tauri-store api changes

**Comment by OnismIS** [comment]
> I have found the source of this issue and it has to do with the new tauri-store api changes我找到了这个问题的根源，它与新的 tauri-store api 更改有关

Thank you，and I can't display subtitles here, do you have any clues？
I tried these three, but none of them worked.
![image](https://github.com/user-attachments/assets/0c50536e-ff08-4419-bc93-e8ce4987ea60)

**Comment by OnismIS** [comment]
Besides, 

> I have found the source of this issue and it has to do with the new tauri-store api changes我找到了这个问题的根源，它与新的 tauri-store api 更改有关

In addition, if I directly click on Watch Now from the homepage, the progress bar of the video will display an error, as shown in the screenshot.
![image](https://github.com/user-attachments/assets/ebdc4d44-4065-4777-ade2-c7add4535db8)
It does not display the total duration and cannot be dragged. If you start playing from anywhere else, this problem will not occur.
