### ISSUE TITLE
[Bug] Episode of One Piece could not be started.

### ISSUE THREAD

**Issue by Lourisk** [prayag17/Blink#420]
**Describe the bug**
I just downloaded and installed Blink, so I tried to start an episode of One Piece (Episode 656, Season 16) and got the error "TypeError: Cannot read properties of undefined (reading 'Id')"

![Screenshot 2024-11-12 234746](https://github.com/user-attachments/assets/bc0c3ecf-3a0b-4419-8bdd-04d11dfd8e79)

This Bug starts at Episode 62, Season 2.

![Screenshot 2024-11-12 235057](https://github.com/user-attachments/assets/93acae54-86b0-46e2-b054-8638b3c3fa3b)

The first Season works perfectly fine.

Screenshot:
![Screenshot 2024-11-13 000144](https://github.com/user-attachments/assets/fd56c216-7767-42c1-a08c-aba8db860597)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: Blink-windows-latest-devaaab6dfd36c715b95dcbeb2466827d19071452f5 (Continuous Integration #555)
 - Jellyfin Version: 10.10.1

**Comment by prayag17** [comment]
Hey @Lourisk, can you try the latest nightly build.

Here is a link to it:
https://github.com/prayag17/Blink/actions/runs/12010190732

**Comment by Lourisk** [comment]
Hey @prayag17,

In the link that you gave me, there are no artifacts to download.

So I tried this nightly build (https://github.com/prayag17/Blink/actions/runs/12010173811).
But I got still an Error.

![Screenshot 2024-11-25 190907](https://github.com/user-attachments/assets/47e3818f-0cdd-44c1-a445-301cdefff7dc)

**Comment by prayag17** [comment]
Hey @Lourisk , I just pushed another commit which might fix this issue. You can try the nightly build from here :
https://github.com/prayag17/Blink/actions/runs/12024019232

Also, are your episode numbered absolutely? (ie. like S03E10 to 120 or something)

**Comment by Lourisk** [comment]
Hey @prayag17
the build you sent me 13 hours ago doesn't work,
but the latest nightly build from 2 hours ago works fine.

Thank you for your work.

**Comment by prayag17** [comment]
Good to know that, I pushed the new index method after I sent you that CI which eliminates the use of indexNumber key

**Comment by Lourisk** [comment]
Hey @prayag17 

I'm reopening this bug because I didn't notice 3 days ago that it was still causing the error.

Now when I start an episode it always plays the first episode of the season and this error is now with every season.

I tried the latest nightly build and this bug is also there.

**Comment by prayag17** [comment]
How do you enable absolute numbering in Jellyfin?

**Comment by prayag17** [comment]
@Lourisk can you try the https://github.com/prayag17/Blink/actions/runs/12094006860 ?

**Comment by Lourisk** [comment]
Hey @prayag17 

Sorry for the late reply.

I tried the build you sent me and the latest build, seems to work now!

![Screenshot 2024-12-03 033615](https://github.com/user-attachments/assets/80c4460d-3f6d-4259-8ccf-185381631e2d)
