### ISSUE TITLE
[Bug] Unable to play certain episodes of animes

### ISSUE THREAD

**Issue by UniOnTheMap** [prayag17/Blink#433]
**Describe the bug**
Pressing play on the first episode of certain animes within the Anime library or on the episodes page of the season will display an error in the bottom left, 

**Known Problematic Episodes**
- Nichijou - My Ordinary Life (2011) - S01E01 - Episode 1 [Bluray-1080p][FLAC 2.0][x264]-URANiME
- Violet Evergarden (2018) - S01E01 - 001 - I Love You and Auto Memoir Dolls [Bluray-1080p][10bit][x265][PCM 2.0][EN+JA]-iAHD
- Arifureta - From Commonplace to World's Strongest (2019) - S01E01 - 001 - The Monster of the Abyss [Bluray-1080p][10bit][x265][TrueHD 2.0][EN+JA]-iAHD

**To Reproduce**
1. Click on a related anime
2. Play the first episode
4. "TypeError: Cannot read properties of undefined (reading 'MediaStreams')" in bottom left

**Expected behavior**
The first episode of the anime should play.

**Screenshots**
![image](https://github.com/user-attachments/assets/0a794cc5-9e13-4a54-b672-4f974ab3ff8f)
![image](https://github.com/user-attachments/assets/98f3cfc9-a5c8-41a7-9bb2-decd08b7375c)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro (10.0.26100 Build 26100)
 - Version: 0.0.7-dev
 - Jellyfin Version: 10.10.3

**Comment by prayag17** [comment]
Hey @UniOnTheMap , can you try latest nightly build and check if this is still an issue? 

Here is a link pointing to it:
https://github.com/prayag17/Blink/actions/runs/12031524688

**Comment by UniOnTheMap** [comment]
Hey, sorry for the late response don't check Github that often, I'm receiving another error now as shown below:

![image](https://github.com/user-attachments/assets/f461f411-dcca-4383-abc3-1691c5c277de)

**Comment by prayag17** [comment]
Can you try https://github.com/prayag17/Blink/actions/runs/12160327649 ?

**Comment by UniOnTheMap** [comment]
Okay, it works when I attempt to play it from the episodes showcase like in the previously provided screenshot however by only searching it and pressing play it returns the same error.

![image](https://github.com/user-attachments/assets/bde7640d-2913-46e0-af03-051b10e2344f)

**Comment by prayag17** [comment]
Can you send a screenshot of the console page in the latest nightyl build? 

https://github.com/prayag17/Blink/actions/runs/12203587691

**Comment by UniOnTheMap** [comment]
Still get the same error code from the previous image, wasn't sure what console you were referring to so I included everything I can think of.

![image](https://github.com/user-attachments/assets/ee915c5c-6716-4960-b3ec-c60c68f12b92)
![image](https://github.com/user-attachments/assets/cb1ea8d5-b3a2-47e8-ae0c-8b76adc86afd)
![image](https://github.com/user-attachments/assets/5ae96ecb-0950-48c8-9bf8-837268b55def)

**Comment by prayag17** [comment]
Is this fixed in the latest nightly?

**Comment by UniOnTheMap** [comment]
This is fixed in the latest nightly build
