### ISSUE TITLE
[Feat] Support for keyboard media control keys on macOS

### ISSUE THREAD

**Issue by foss-** [prayag17/Blink#435]
**Is your feature request related to a problem? Please describe.**
Interestingly pressing F8 (Play, Pause) is recognized as expected.
Pressing F7 (back) or F9 (forward) is not recognized and not functional.

**Describe the solution you'd like**
Unsure if this is an error in implementation that needs to be addressed (bug) or if functionality just has not been added yet (feature). In the latter case it would be even more fascination that the play pause key does work fine :)

**Describe alternatives you've considered**
Use on-screen controls in Blink but hardware keys is always faster and easier.

**Additional context**
macOS 15.1.1
Blink 0.0.7-dev (20241123.175537)

**Comment by prayag17** [comment]
Macos keyboard controls are certainly a feature still not properly added to Blink. It would be nice if you can list out all the typical keyboard controls present in Macos for media control.

**Comment by foss-** [comment]
### Media Control Keys on macOS:
1. **Play/Pause (`F8`)**  
   - Controls play/pause for media playback.

2. **Rewind (`F7`)**  
   - Skips to the previous track or restarts the current track. 
   - If held down, it performs fast reverse.

3. **Fast-Forward (`F9`)**  
   - Skips to the next track.
   - If held down, it performs fast forward.

Do you need the other control keys controlling volume and brightness? From my understanding both aspects should be handled by macOS.

**Comment by foss-** [comment]
### Media Control Keys on macOS (Volume):

4. **Mute (`F10`)**  
   - Toggles mute for system audio.

5. **Volume Down (`F11`)**  
   - Decreases system audio volume.

6. **Volume Up (`F12`)**  
   - Increases system audio volume.

**Comment by prayag17** [comment]
I have just pushed a commit implementing basic onPress key binding for MacOS, this does not include holding the key to perform different actions. Also I have decided not to mess with the default key binding for system audio.
