### ISSUE TITLE
Could not create default EGL display: EGL_BAD_PARAMETER. Aborting...

### ISSUE THREAD

**Issue by martian0x80** [prayag17/Blink#450]
**Describe the bug**
I get a blank screen when I launch the AppImage, here's what it logs to the terminal:
`Could not create default EGL display: EGL_BAD_PARAMETER. Aborting...`

**To Reproduce**
1. Launch the AppImage.

**Expected behavior**
Should run.

**Screenshots**
Just a blank screen.

**Desktop (please complete the following information):**
 - OS: EndeavourOS
 - Version: 0.0.7-dev
 - Jellyfin Version: 10.10.3
 - Wayland Compositor: Hyprland

**Comment by prayag17** [comment]
this error has to do with your system's libwebkit2gtk package. You can try downgrading or upgrading it to a specific version
