### ISSUE TITLE
[Windows] Failed to install WebView2

### ISSUE THREAD

**Issue by Memhave** [prayag17/Blink#451]
**Describe the bug**
Attempt to install Blink on Windows

**To Reproduce**
1. Download Latest
2. Click on Install

**Expected behavior**
Application installs

**Screenshots**
[imagine if this was the install dialogue]
Downloading WebView2 bootstrapper...
WebView2 bootstrapper downloaded successfully
Installing WebView2...
Execute: C:\Users\****\AppData\Local\Temp\MicrosoftEdgeWebview2Setup.exe /silent /install
Error: Installing WebView2 failed with exit code -2147219426
Failed to install WebView2! The app can't run without it. Try restarting the installer.

**Desktop (please complete the following information):**
 - OS: Windows 11 Enterprise N
 - Version 22H2 / 22621.2361 / Windows Feature Experience Pack 1000.22674.1000.0
 - Jellyfin Version [e.g. 10.9]: N/A
 
**Additional context**
 - Not sure if relevant but attempting to install on a different drive
    - Attempted install location to D:\Programs\Blink
 - Ran with and without as admin

**Comment by prayag17** [comment]
Have you disabled Edge's auto update feature?

**Comment by Memhave** [comment]
If you're talking about Microsoft Edge then yes - Edge is not on my system and has been removed for a long time.

I hope thats not a dependency :/

**Comment by prayag17** [comment]
It's not a dependency but removing it does cause webView2 to be removed from the system. You can search for ways to install WebView2 without edge

**Comment by Memhave** [comment]
I see thanks.
