### ISSUE TITLE
[Bug] OVA, Prologue, and Special Episodes: Missing Thumbnails, Incorrect Layouts, and more

### ISSUE THREAD

**Issue by UniOnTheMap** [prayag17/Blink#458]
**Describe the bug**
OVAs, Prologues and other non-traditional episode content for Anime and TV Shows will show in the episodes list of its respective season regardless of if it is downloaded and will display an incorrect layout number, thumbnail and duration.

**Animes - Problematic**
- Arifureta: From Commonplace to World's Strongest
- Nichijou - My Ordinary Life

**TV Shows - Problematic**
- Futurama

**To Reproduce**
1. Click on a problematic tv show or anime
3. Scroll down to the episodes list
4. **See visual bug**
5. Attempt to play the episode
6. **"No media source ID found" in the bottom left**

**Screenshots**
![image](https://github.com/user-attachments/assets/7c063e52-ed19-4475-a7e5-a43df8912112)
![image](https://github.com/user-attachments/assets/8954cd3f-8797-4442-b3c7-5a7708b7b92b)
![image](https://github.com/user-attachments/assets/bf2f12c2-95c5-4f38-86ec-6ce54d80a649)
![image](https://github.com/user-attachments/assets/b663afc8-e0b1-4323-995e-ca88fa0c813a)
![image](https://github.com/user-attachments/assets/7d6e88e9-9bb5-4932-b0b3-0037e274469d)
![image](https://github.com/user-attachments/assets/98aa1b45-c53a-4e40-92c5-cb1570e891ca)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro (10.0.26100 Build 26100)
 - Version: 0.0.7-dev
 - Jellyfin Version: 10.10.3

**Comment by prayag17** [comment]
Can try the latest nightly build and see if this is still persistent?

**Comment by UniOnTheMap** [comment]
Can confirm this is fixed in the latest nightly build

**Comment by prayag17** [comment]
Nice, I will close this issue then
