### ISSUE TITLE
Cant play any media

### ISSUE THREAD

**Issue by EdgeLord69-dev** [prayag17/Blink#462]
**Describe the bug**
Whenever i try to play any media through Blink, it shows AxiosError: Request failed with Status Code 404

**To Reproduce**
1. Go to any media library
2. Click on any episode
3. See error

**Expected behavior**
The media should play through Blink
**Screenshots**
![image](https://github.com/user-attachments/assets/9e3e6fd0-192b-4170-babc-34cbb79cfa45)
![image](https://github.com/user-attachments/assets/75387ab5-3c74-42e9-8a33-8b8e3348cedb)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.0.0 - Alpha 3
 - Jellyfin Version: 10.9.9

**Comment by prayag17** [comment]
Share a screenshot of the console using the nightly build:

https://github.com/prayag17/Blink/actions/runs/12276163530

**Comment by EdgeLord69-dev** [comment]
excuse my ignorance, but how do i access the console in the nightly build?
Is it the command prompt window that opens?

**Comment by prayag17** [comment]
You can access the console by using the Ctrl+Shift+I shortcut

**Comment by EdgeLord69-dev** [comment]
![image](https://github.com/user-attachments/assets/ed15d746-b433-4953-8aa4-b641baccba5b)
I have blurred only my ip adress from showing up in the screenshots

**Comment by EdgeLord69-dev** [comment]
I think it was a problem with my server, as I reinstalled Jellyfin & it fixed the issue. Closing now.
