### ISSUE TITLE
Connection to `tracker0.ufibox.com` on startup

### ISSUE THREAD

**Issue by parasiteoflife** [prayag17/Blink#463]
**Describe the bug**
Why the latest Windows build tries to connect to `tracker0.ufibox.com` on startup? I just installed Blink and auto-launch it, some seconds later (Didn't touched the Blink window) it tried to contact `tracker0.ufibox.com`, why?

It also tried to contact `ufibox.com` and `rawcdn.githack.com` (this one it retries several times)  
I see at least the later one it's like a proxy cdn, but why is this needed? This is a desktop software, do we really need to download the cdn instead of including the assets directly?

**Comment by prayag17** [comment]
rawcdn.githack.com is for checking updates from latest.json present in this repo, but as for tracker0.ufibox.com I don't think its a part of this application maybe it it caused by the localhost script left behind by the react-devtools.
