### ISSUE TITLE
[Bug] Video player takes long time to load

### ISSUE THREAD

**Issue by EdgeLord69-dev** [prayag17/Blink#473]
**Describe the bug**
Any show or episode just refuses to play. I waited for around 30mins for it to load but the playback was just buffering

**To Reproduce**
1. Play any video
**Expected behavior**
The video should play smoothly

**Screenshots**
![image](https://github.com/user-attachments/assets/4664cc05-df50-43a6-a072-7559de4444c9)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version Alpha 3
 - Jellyfin Version 10.9
**Additional context**
I had a similar problem to #467 earlier which was fixed in my case by resetting the jellyfin server.

**Comment by prayag17** [comment]
Your media might not be supported by Blink or it is transcoding which would take time on a slow server. You can check if your media is transcoding by going to the dashboard in the web client and clicking the info icon below the blink client

**Comment by EdgeLord69-dev** [comment]
I dont think it is a server issue as the media was playing perfectly when viewed from the web client or Jellyfin Media Player

**Comment by prayag17** [comment]
Hey @EdgeLord69-dev, I just pushed a commit which fixes this issue. You can verify it by downloading the nighlty build https://github.com/prayag17/Blink/actions/runs/12525235230
