### ISSUE TITLE
HEVC Support

### ISSUE THREAD

**Issue by EdgeLord69-dev** [prayag17/Blink#476]
**Is your feature request related to a problem? Please describe.**
Blink cannot play any content encoded in hevc or x265, since hevc is now becoming very popular for distributing media, blink not supporting it means that it cannot play most media on my device

**Describe the solution you'd like**
I would like that Blink would start support HEVC 10bit content, since it already support av1, which is the second most popular video codec right now

**Describe alternatives you've considered**
For now, i am just playing y media through JFM, but i would like blink to support HEVC since it has a really nice ui compared to JFM.

**Comment by prayag17** [comment]
Blink only supports codecs supported by your device, check if you have the HEVC codec pack installed from the Microsoft store
