### ISSUE TITLE
[Feat] Discord RPC

### ISSUE THREAD

**Issue by ohitstom** [prayag17/Blink#93]
Once playback has been added, discord RPC capabilities would be really awesome.

There are a few jellyfin related projects that achieve this already but not in a seamless way, e.g jellyfin-rpc needing a running service, the PR for jellyfin-media-player being untouched for months, etc.|

Stuff like this would really set this project apart form jellyfin-media-player

**Comment by prayag17** [comment]
Good idea actually, will add it in Alpha 2
